@api = http://localhost:3000/api/auth


POST {{api}}/login
Content-Type: application/json

{
    "email": "mastrocoding@gmail.com",
    "password": "asdlkfjalsdf"
}
###

POST {{api}}/register
Content-Type: application/json

{
    "name": "Mohamed",
    "email": "mastrocoding@gmail.com",
    "password": "asdlkfjalsdf"
}

###
GET {{api}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hc3Ryb2NvZGluZ0BnbWFpbC5jb20iLCJzdWIiOiI2NDk1MzYxYzY0MjBkNjE1YTEwNmY4NWQiLCJpYXQiOjE2ODc1MjUxMDEsImV4cCI6MTY4ODEyOTkwMX0.lSkMZUbgho9cpC1nmFR_b4bZPdN4aKa_WaZ4HuAmkdw